- hosts: all
  become: true
  tasks:
    - name: delete old deployment
      environment:
        KUBECONFIG: /home/ubuntu/.kube/config
      command: kubectl delete -f /home/ubuntu/deployment.yml
    - name: delete old service
      environment:
        KUBECONFIG: /home/ubuntu/.kube/config
      command: kubectl delete -f /home/ubuntu/service.yml
    - name: create new deployment
      environment:
        KUBECONFIG: /home/ubuntu/.kube/config
      command: kubectl apply -f /home/ubuntu/deployment.yml
    - name: create new service
      environment:
        KUBECONFIG: /home/ubuntu/.kube/config
      command: kubectl apply -f /home/ubuntu/service.yml
