kind: Service                             
apiVersion: v1
metadata:
  name: mrkordy
  labels:
    app: mrkordy
spec:
  ports:
    - port: 8080                               
      targetPort: 80                    
      nodePort: 31200
  selector:
    app: mrkordy               
  type: LoadBalancer                   